---
title: "Calendar for 500: Spring 2023"
date-modified: last-modified
---

This Calendar serves as the final word on all deadlines, deliverables and class sessions. 

## Readings

During the course, we will read Paul Rosenbaum's book **Observation and Experiment: An Introduction to Causal Inference**, which is available as an e-book or in paperback for under $40. Please read the Preface and Chapter 1 before our first class on 2022-01-19. 

## Timing and Location

- All classes are held in Wolstein Research Building, Room 1217.
- Classes 01, 14 and 15 will begin at 8:30 AM and continue until 11 AM.
- Classes 02-13 will begin at 9:00 AM and continue until 11 AM.

## March 2023

LINK | Date | Description
---------: | :-------: | :-----------------------------------------------------
[Lab 3](lab3.qmd) | 03-01 | [Lab 3](lab3.qmd) due to [Canvas](https://canvas.case.edu/) at 7 PM
[Class 07](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class07) | 03-02 | Propensity Scores VI: Demonstration
[OSIA Form](https://bit.ly/500-2023-osia-schedule) | 03-06 | Complete [OSIA scheduling/second reader form](https://bit.ly/500-2023-osia-schedule) by Noon
[Proposal 2](proj500.qmd) | 03-08 | [Project Proposal (Final version)](proj500.qmd) due to [Canvas](https://canvas.case.edu/) at 7 PM
[Class 08](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class08) | 03-09 | Rosenbaum Chapter 7, Sensitivity Analyses
No Class | 03-16 | CWRU Spring Break (03-13 through 03-17)
[Lab 4](lab4.qmd) | 03-22 | [Lab 4](lab4.qmd) due to [Canvas](https://canvas.case.edu/) at 7 PM
[Class 09](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class09) | 03-23 | [OSIA](osia.qmd) Group 1, Rosenbaum Chapter 11
[Lab 5](lab5.qmd) | 03-29 | [Lab 5](lab5.qmd) due to [Canvas](https://canvas.case.edu/) at 7 PM
[Class 10](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class10) | 03-30 | [OSIA](osia.qmd) Group 2, Rosenbaum Chapter 9

## April and May 2023

LINK | Date | Description
---------: | :-------: | :-----------------------------------------------------
[Update](proj500.qmd) | 04-05 | Project Update due to [Canvas](https://canvas.case.edu/) at 7 PM
[Class 11](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class11) | 04-06 | [OSIA](osia.qmd) Group 3, Project Updates discussion
[Class 12](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class12) | 04-13 | Final OSIA talk, Instrumental Variables, Rosenbaum Chapter 8
[Class 13](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class13) | 04-20 | Recent Work, Rosenbaum Chapter 12
[Class 14](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class14) | 04-27 | (8:30 - 11 AM) Project Presentations, I
[Class 15](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class15) | 05-04 | (8:30 - 11 AM) Project Presentations, II

## End of Semester

- Final Project Submissions are due to Canvas at **12 Noon on Monday 2023-05-08** from everyone.
- When prompted via email by the University (usually in late April), please visit <https://webapps.case.edu/courseevals/> and complete the course evaluations before they close.


## January 2023

LINK | Date | Description
---------: | :-------: | :-----------------------------------------------------
[Class 01](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class01) | 01-19 | (8:30 - 11 AM) Rosenbaum Preface & Chapter 1, Introduction
[Lab 0](lab0.qmd) | 01-26 | Read through the [Lab 0 example](lab0.qmd) before Class 02. Can you replicate it?
[Class 02](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class02) | 01-26 | Rosenbaum Chapter 2, Propensity Scores I


## February 2023

LINK | Date | Description
---------: | :-------: | :-----------------------------------------------------
[Lab 1](lab1.qmd) | 02-01 | [Lab 1](lab1.qmd) due to [Canvas](https://canvas.case.edu/) at 7 PM
[Class 03](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class03) | 02-02 | Rosenbaum Chapter 3, Propensity Scores II
[Lab 2](lab2.qmd) | 02-08 | [Lab 2](lab2.qmd) due to [Canvas](https://canvas.case.edu/) at 7 PM
[Class 04](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class04) | 02-09 | The Toy Example, Propensity Scores III
[OSIA](osia.qmd) | 02-15 | [OSIA Claims](osia.qmd) due at 7 PM via email to Dr. Love
[Class 05](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class05) | 02-16 | Rosenbaum Chapter 4, Project Discussion, Propensity Scores IV
[Proposal 1](proj500.qmd) | 02-22 | [Project Proposal (draft 1)](proj500.qmd) due to [Canvas](https://canvas.case.edu/) at 7 PM
[Class 06](https://github.com/THOMASELOVE/500-classes-2023/tree/main/class06) | 02-23 | Rosenbaum Chapters 5-6, Propensity Scores V

